# Welcome to Jekyll!
#

# Site settings
title: Blue Canary
tagline: Belgian Cyber Security Firm
description: Blue Canary focusses on assisting businesses to gain insight and increasing their current cyber security maturity.
og:description: Blue Canary focusses on assisting businesses to gain insight and increasing their current cyber security maturity.
owner: Blue Canary # or company name
first_published: 2019 # if migrating another site, the year of your first publish
email: dennis@bluecanary.be
#baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.bluecanary.be" # the base hostname & protocol for your site
logo: https://raw.githubusercontent.com/faun88/BlueCanary/master/images/logo_transparant.png
social:
  github: https://github.com/bluecanarybe
  linkedin-square: https://linkedin.com/in/dennis-m-42b58926
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
plugins:
  - jekyll-seo-tag
